name: Build Keycloak JAR
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Set up Java 17
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Compile and Package JAR
      run: mvn clean package

    - name: Upload Finished JAR
      uses: actions/upload-artifact@v4
      with:
        name: keycloak-plugin
        path: target/keycloak-pushover-notifier.jar
